'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class forceupgrade
    
    '''<summary>
    '''pnlForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlAccountsSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccountsSP As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlPassEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPassEntry As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlPassEntryReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPassEntryReview As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''fldSubmittedPassList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldSubmittedPassList As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''cmdRemoveSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRemoveSelected As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlPassEntryAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPassEntryAdd As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''fldNewPassMediaNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldNewPassMediaNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmdAcctSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAcctSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fldNewAccessoOrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldNewAccessoOrderID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fldComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldComment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fldMediaNumberToAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldMediaNumberToAssign As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fldAmountToAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldAmountToAssign As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmdAccountsSPBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAccountsSPBack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdAccountsSPNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAccountsSPNext As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlAssignConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAssignConfirm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblConfirmText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmdConfirmCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConfirmCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdComfirmExecute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdComfirmExecute As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlThankYou control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlThankYou As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblThankYou control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThankYou As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmdThankYouContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdThankYouContinue As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hidMediaNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMediaNumber As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidParkID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidParkID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidBucksCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidBucksCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidFolioUniqueID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidFolioUniqueID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidMemberUpgradeRequestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMemberUpgradeRequestID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PassholderAdmin.Admin
        Get
            Return CType(MyBase.Master,PassholderAdmin.Admin)
        End Get
    End Property
End Class
