'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class upgradereviewitem
    
    '''<summary>
    '''pnlForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlPageInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPageInfo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cmdCancelOldOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancelOldOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdMessage As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fldMemberUpgradeRequestStatusID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldMemberUpgradeRequestStatusID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmdPreviousRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPreviousRecord As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdReturnToList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdReturnToList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdNextRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNextRecord As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlSendMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSendMessage As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''fldSendMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldSendMessage As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''fldMessageSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldMessageSubject As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fldMessageEmailDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldMessageEmailDrop As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''fldMessageEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldMessageEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fldMessageEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldMessageEditor As Global.Telerik.Web.UI.RadEditor
    
    '''<summary>
    '''cmdSendMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSendMessage As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdCancelMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancelMessage As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''litRequestInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRequestInfo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlOldOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOldOrder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litOriginalOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOriginalOrder As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lstOldItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstOldItems As Global.Telerik.Web.UI.RadListBox
    
    '''<summary>
    '''pnlOldPasses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOldPasses As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litOldPasses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOldPasses As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lstOldPasses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstOldPasses As Global.Telerik.Web.UI.RadListBox
    
    '''<summary>
    '''pnlRefundInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRefundInfo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblRefundGuidance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefundGuidance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fldRefundAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldRefundAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmdRefundSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefundSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdRefundEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefundEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNewOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewOrder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litNewOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litNewOrder As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lstNewItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstNewItems As Global.Telerik.Web.UI.RadListBox
    
    '''<summary>
    '''pnlPromoInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPromoInfo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''promoConsiderationGuidance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents promoConsiderationGuidance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fldConsiderationAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldConsiderationAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmdPromoSaveEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPromoSaveEdit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fldNewOrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldNewOrderID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''fldOldOrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldOldOrderID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''fldMemberUpgradeRequestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldMemberUpgradeRequestID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''fldMemberUpgradeRequestTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldMemberUpgradeRequestTypeID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''fldRefundRecommended control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldRefundRecommended As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''fldRefundDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldRefundDescription As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''fldRefundDescriptionForGuest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldRefundDescriptionForGuest As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PassholderAdmin.Admin
        Get
            Return CType(MyBase.Master,PassholderAdmin.Admin)
        End Get
    End Property
End Class
