'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class upgradereview
    
    '''<summary>
    '''pnlForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''fldMemberUpgradeRequestStatusID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldMemberUpgradeRequestStatusID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''fldParkID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldParkID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmdPromoCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPromoCredit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReport As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''QueryTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QueryTypeID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PassholderAdmin.Admin
        Get
            Return CType(MyBase.Master,PassholderAdmin.Admin)
        End Get
    End Property
End Class
